# Generated by Django 6.1.1 on 2026-10-05 22:58

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cadastros", "0002_produto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContadorPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ultimo_numero",
                    models.PositiveIntegerField(default=0, verbose_name="Último número"),
                ),
            ],
            options={
                "verbose_name": "contador de pedidos",
                "verbose_name_plural": "contador de pedidos",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="contador_pedido_linha_unica"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Número"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("confirmado", "Confirmado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="rascunho",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "confirmado_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="Confirmado em"),
                ),
                (
                    "cancelado_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="Cancelado em"),
                ),
                (
                    "motivo_cancelamento",
                    models.TextField(blank=True, verbose_name="Motivo do cancelamento"),
                ),
                (
                    "desconto_tipo",
                    models.CharField(
                        choices=[("reais", "R$"), ("percentual", "%")],
                        default="percentual",
                        max_length=10,
                        verbose_name="Tipo de desconto",
                    ),
                ),
                (
                    "desconto_informado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Desconto informado",
                    ),
                ),
                (
                    "desconto_valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Desconto (R$)",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12, verbose_name="Total"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, max_length=1000, verbose_name="Observações"),
                ),
                (
                    "cancelado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cancelado por",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="cadastros.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "confirmado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Confirmado por",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "pedido",
                "verbose_name_plural": "pedidos",
            },
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codigo", models.CharField(max_length=30, verbose_name="Código")),
                ("descricao", models.CharField(max_length=200, verbose_name="Descrição")),
                ("quantidade", models.PositiveIntegerField(verbose_name="Quantidade")),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Preço unitário"
                    ),
                ),
                (
                    "custo_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="Custo unitário",
                    ),
                ),
                (
                    "desconto_rateado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Desconto rateado",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_de_pedido",
                        to="cadastros.produto",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="pedidos.pedido",
                        verbose_name="Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "item do pedido",
                "verbose_name_plural": "itens do pedido",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(
                fields=["status", "confirmado_em"], name="pedido_status_confirmado_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pedido",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("numero__isnull", True), ("status", "rascunho")),
                    models.Q(
                        models.Q(("status", "rascunho"), _negated=True), ("numero__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="pedido_numero_so_fora_do_rascunho",
            ),
        ),
        migrations.AddConstraint(
            model_name="pedido",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("desconto_informado__gte", 0),
                    ("desconto_valor__gte", 0),
                    ("subtotal__gte", 0),
                    ("total__gte", 0),
                ),
                name="pedido_valores_nao_negativos",
            ),
        ),
        migrations.AddConstraint(
            model_name="itempedido",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantidade__gt", 0)), name="item_quantidade_positiva"
            ),
        ),
        migrations.AddConstraint(
            model_name="itempedido",
            constraint=models.UniqueConstraint(
                fields=("pedido", "produto"), name="item_produto_unico_no_pedido"
            ),
        ),
    ]
