# Generated by Django 6.1.1 on 2026-10-05 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cadastros", "0002_produto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimentoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("inicial", "Estoque inicial"),
                            ("entrada", "Entrada"),
                            ("saida", "Saída por pedido"),
                            ("devolucao", "Devolução por cancelamento"),
                            ("ajuste_mais", "Ajuste (+)"),
                            ("ajuste_menos", "Ajuste (−)"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(verbose_name="Quantidade")),
                (
                    "custo_unitario",
                    models.DecimalField(
                        decimal_places=4, max_digits=14, verbose_name="Custo unitário"
                    ),
                ),
                ("estoque_apos", models.IntegerField(verbose_name="Estoque após o movimento")),
                (
                    "custo_medio_apos",
                    models.DecimalField(
                        decimal_places=4, max_digits=14, verbose_name="Custo médio após o movimento"
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Observação ou motivo"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentos",
                        to="cadastros.produto",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimento de estoque",
                "verbose_name_plural": "movimentos de estoque",
                "ordering": ["-criado_em", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantidade__gt", 0)),
                        name="movimento_quantidade_positiva",
                    )
                ],
            },
        ),
    ]
