# Generated by Django 6.1.1 on 2026-10-05 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estoque", "0001_initial"),
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentoestoque",
            name="pedido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimentos",
                to="pedidos.pedido",
                verbose_name="Pedido",
            ),
        ),
    ]
