# Generated by Django 6.1.1 on 2026-10-05 03:00

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import apps.contas.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="e-mail")),
                ("nome", models.CharField(max_length=150, verbose_name="nome")),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, verbose_name="acesso ao painel de manutenção"
                    ),
                ),
                (
                    "deve_trocar_senha",
                    models.BooleanField(default=True, verbose_name="deve trocar a senha"),
                ),
                (
                    "codigos_recuperacao_entregues",
                    models.BooleanField(
                        default=False, verbose_name="códigos de recuperação entregues"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criado em"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuário",
                "verbose_name_plural": "usuários",
            },
            managers=[
                ("objects", apps.contas.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalUsuario",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254, verbose_name="e-mail")),
                ("nome", models.CharField(max_length=150, verbose_name="nome")),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, verbose_name="acesso ao painel de manutenção"
                    ),
                ),
                (
                    "deve_trocar_senha",
                    models.BooleanField(default=True, verbose_name="deve trocar a senha"),
                ),
                (
                    "codigos_recuperacao_entregues",
                    models.BooleanField(
                        default=False, verbose_name="códigos de recuperação entregues"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical usuário",
                "verbose_name_plural": "historical usuários",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
