# Generated by Django 6.1.1 on 2026-10-05 03:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contas", "0002_perfis"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email_tentado", models.CharField(max_length=254, verbose_name="e-mail tentado")),
                ("sucesso", models.BooleanField(verbose_name="sucesso")),
                ("motivo", models.CharField(blank=True, max_length=100, verbose_name="motivo")),
                ("ip", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP")),
                (
                    "navegador",
                    models.CharField(blank=True, max_length=300, verbose_name="navegador"),
                ),
                (
                    "quando",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="quando"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acessos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de acesso",
                "verbose_name_plural": "registros de acesso",
                "ordering": ["-quando"],
            },
        ),
    ]
