# Generated by Django 6.1.1 on 2026-10-05 06:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        UnaccentExtension(),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("PF", "Pessoa"), ("PJ", "Empresa")],
                        default="PJ",
                        max_length=2,
                        verbose_name="Tipo",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "documento",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF/CNPJ"),
                ),
                ("telefone", models.CharField(blank=True, max_length=30, verbose_name="Telefone")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="E-mail")),
                ("cep", models.CharField(blank=True, max_length=8, verbose_name="CEP")),
                (
                    "logradouro",
                    models.CharField(blank=True, max_length=200, verbose_name="Logradouro"),
                ),
                ("numero", models.CharField(blank=True, max_length=20, verbose_name="Número")),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=100, verbose_name="Complemento"),
                ),
                ("bairro", models.CharField(blank=True, max_length=100, verbose_name="Bairro")),
                ("cidade", models.CharField(blank=True, max_length=100, verbose_name="Cidade")),
                (
                    "uf",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "AC"),
                            ("AL", "AL"),
                            ("AP", "AP"),
                            ("AM", "AM"),
                            ("BA", "BA"),
                            ("CE", "CE"),
                            ("DF", "DF"),
                            ("ES", "ES"),
                            ("GO", "GO"),
                            ("MA", "MA"),
                            ("MT", "MT"),
                            ("MS", "MS"),
                            ("MG", "MG"),
                            ("PA", "PA"),
                            ("PB", "PB"),
                            ("PR", "PR"),
                            ("PE", "PE"),
                            ("PI", "PI"),
                            ("RJ", "RJ"),
                            ("RN", "RN"),
                            ("RS", "RS"),
                            ("RO", "RO"),
                            ("RR", "RR"),
                            ("SC", "SC"),
                            ("SP", "SP"),
                            ("SE", "SE"),
                            ("TO", "TO"),
                        ],
                        max_length=2,
                        verbose_name="UF",
                    ),
                ),
                ("observacoes", models.TextField(blank=True, verbose_name="Observações")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCliente",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("PF", "Pessoa"), ("PJ", "Empresa")],
                        default="PJ",
                        max_length=2,
                        verbose_name="Tipo",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "documento",
                    models.CharField(db_index=True, max_length=14, verbose_name="CPF/CNPJ"),
                ),
                ("telefone", models.CharField(blank=True, max_length=30, verbose_name="Telefone")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="E-mail")),
                ("cep", models.CharField(blank=True, max_length=8, verbose_name="CEP")),
                (
                    "logradouro",
                    models.CharField(blank=True, max_length=200, verbose_name="Logradouro"),
                ),
                ("numero", models.CharField(blank=True, max_length=20, verbose_name="Número")),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=100, verbose_name="Complemento"),
                ),
                ("bairro", models.CharField(blank=True, max_length=100, verbose_name="Bairro")),
                ("cidade", models.CharField(blank=True, max_length=100, verbose_name="Cidade")),
                (
                    "uf",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "AC"),
                            ("AL", "AL"),
                            ("AP", "AP"),
                            ("AM", "AM"),
                            ("BA", "BA"),
                            ("CE", "CE"),
                            ("DF", "DF"),
                            ("ES", "ES"),
                            ("GO", "GO"),
                            ("MA", "MA"),
                            ("MT", "MT"),
                            ("MS", "MS"),
                            ("MG", "MG"),
                            ("PA", "PA"),
                            ("PB", "PB"),
                            ("PR", "PR"),
                            ("PE", "PE"),
                            ("PI", "PI"),
                            ("RJ", "RJ"),
                            ("RN", "RN"),
                            ("RS", "RS"),
                            ("RO", "RO"),
                            ("RR", "RR"),
                            ("SC", "SC"),
                            ("SP", "SP"),
                            ("SE", "SE"),
                            ("TO", "TO"),
                        ],
                        max_length=2,
                        verbose_name="UF",
                    ),
                ),
                ("observacoes", models.TextField(blank=True, verbose_name="Observações")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Criado em"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical cliente",
                "verbose_name_plural": "historical clientes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
