# Generated by Django 6.1.1 on 2026-10-05 22:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalProduto",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        error_messages={"unique": "Já existe um produto com este código."},
                        max_length=30,
                        verbose_name="Código",
                    ),
                ),
                ("descricao", models.CharField(max_length=200, verbose_name="Descrição")),
                ("marca", models.CharField(max_length=60, verbose_name="Marca")),
                (
                    "preco",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Preço"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Criado em"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical produto",
                "verbose_name_plural": "historical produtos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        error_messages={"unique": "Já existe um produto com este código."},
                        max_length=30,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("descricao", models.CharField(max_length=200, verbose_name="Descrição")),
                ("marca", models.CharField(max_length=60, verbose_name="Marca")),
                (
                    "preco",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Preço"),
                ),
                (
                    "custo_medio",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        editable=False,
                        max_digits=14,
                        verbose_name="Custo médio",
                    ),
                ),
                ("estoque", models.IntegerField(default=0, editable=False, verbose_name="Estoque")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "produto",
                "verbose_name_plural": "produtos",
                "ordering": ["codigo"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("estoque__gte", 0)), name="produto_estoque_nao_negativo"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("preco__gte", 0)), name="produto_preco_nao_negativo"
                    ),
                ],
            },
        ),
    ]
